name: vav
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - theano
    - mujoco_py
    - gym
    - pyopengl
    - numpy
    - pymc
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - scipy
    - argh
    - fire
    - joblib
    - torch
    # Dev dependencies
    - mypy
    - pylint
    - black
